/**
 * Data Loader — fetches JSON/MD files from deployed data directory
 * Legend Team — read-only viewer (v0.3.0)
 *
 * Loading priority:
 *   getTopicIndex() → tries published manifest first, falls back to raw topic_index
 *   getReport()     → uses reportPath-relative paths
 */

const DATA_BASE = './data';

const DataLoader = {
  _cache: {},

  async fetchJSON(filePath) {
    const key = `json:${filePath}`;
    if (this._cache[key]) return this._cache[key];
    try {
      const res = await fetch(`${DATA_BASE}/${filePath}`);
      if (!res.ok) return null;
      const data = await res.json();
      this._cache[key] = data;
      return data;
    } catch (e) {
      console.warn(`[DataLoader] Failed to fetch ${filePath}:`, e);
      return null;
    }
  },

  async fetchMD(filePath) {
    const key = `md:${filePath}`;
    if (this._cache[key]) return this._cache[key];
    try {
      const res = await fetch(`${DATA_BASE}/${filePath}`);
      if (!res.ok) return null;
      const text = await res.text();
      this._cache[key] = text;
      return text;
    } catch (e) {
      console.warn(`[DataLoader] Failed to fetch ${filePath}:`, e);
      return null;
    }
  },

  // ── Published manifest (viewer-facing, generated by build.js) ────────────

  /** Viewer-facing topic list. Generated by build.js from topic_index.json. */
  async getPublishedManifest() {
    return this.fetchJSON('published/topics_manifest.json');
  },

  /** Viewer-facing decision summary. Generated by build.js from decision_ledger.json. */
  async getPublishedDecisions() {
    return this.fetchJSON('published/decisions_summary.json');
  },

  // ── Topic index (prefers published manifest, falls back to raw) ───────────

  /**
   * Returns topic list. Prefers published manifest (topics_manifest.json).
   * Falls back to raw memory/shared/topic_index.json if published is unavailable.
   * Normalizes result to { topics: [...], lastUpdated } shape.
   */
  async getTopicIndex() {
    const published = await this.getPublishedManifest();
    if (published && Array.isArray(published.topics)) {
      return {
        topics: published.topics,
        lastUpdated: published.generatedAt ?? null,
        _source: 'published',
      };
    }
    // Fallback: raw topic_index
    const raw = await this.fetchJSON('memory/shared/topic_index.json');
    if (raw) {
      return { ...raw, _source: 'raw' };
    }
    return null;
  },

  // ── Core data accessors ───────────────────────────────────────────────────

  async getDecisionLedger() {
    // Prefer published decisions summary; fallback to raw
    const published = await this.getPublishedDecisions();
    if (published && Array.isArray(published.decisions)) {
      return { decisions: published.decisions, _source: 'published' };
    }
    return this.fetchJSON('memory/shared/decision_ledger.json');
  },

  async getCurrentSession() {
    return this.fetchJSON('memory/sessions/current_session.json');
  },

  async getSessionIndex() {
    return this.fetchJSON('memory/sessions/session_index.json');
  },

  async getTokenLog() {
    return this.fetchJSON('memory/sessions/token_log.json');
  },

  async getSystemState() {
    return this.fetchJSON('memory/shared/system_state.json');
  },

  async getProjectCharter() {
    return this.fetchJSON('memory/shared/project_charter.json');
  },

  async getMasterFeedback() {
    return this.fetchJSON('memory/master/master_feedback_log.json');
  },

  async getRoleMemory(role) {
    return this.fetchJSON(`memory/roles/${role}_memory.json`);
  },

  async getGlossary() {
    return this.fetchJSON('memory/shared/glossary.json');
  },

  async getEvidenceIndex() {
    return this.fetchJSON('memory/shared/evidence_index.json');
  },

  async getDashboardData() {
    return this.fetchJSON('memory/shared/dashboard_data.json');
  },

  // ── Report fetching ───────────────────────────────────────────────────────

  /**
   * Fetch a report file by reportPath + fileName.
   * reportPath: e.g. "2026-04-04_local-vs-server" (relative to reports/)
   * fileName:   e.g. "ace_rev01.md"
   */
  async getReport(reportPath, fileName) {
    if (fileName) {
      return this.fetchMD(`reports/${reportPath}/${fileName}`);
    }
    // Legacy: single-argument path passed directly
    return this.fetchMD(`reports/${reportPath}`);
  },

  // ── Legacy compat ─────────────────────────────────────────────────────────

  /** @deprecated Use getPublishedManifest() instead */
  async getManifest() {
    return this.fetchJSON('manifest.json');
  },

  // ── Cache ─────────────────────────────────────────────────────────────────

  clearCache() {
    this._cache = {};
  }
};
